# @package _global_

embodiment_tag_to_projector_index:
  real_gr1_arms_only: 0
  real_gr1_arms_only_annotated: 1
  real_gr1_arms_waist: 2
  real_gr1_arms_waist_annotated: 3
  dexmg_gr1_arms_only_inspire: 4
  dexmg_gr1_arms_only_fourier: 5
  dexmg_gr1_arms_waist_fourier: 6
  robocasa_single_arm: 7
  onex_eve_gripper: 8
  robocasa_gr1_arms_only_inspire_hands: 9
  robocasa_gr1_arms_only_fourier_hands: 10
  robocasa_gr1_fixed_lower_body_inspire_hands: 11
  robocasa_gr1_fixed_lower_body_fourier_hands: 12
  robocasa_panda_omron: 13
  # s: 14
  robocasa_bimanual_panda_parallel_gripper: 15
  robocasa_bimanual_panda_inspire_hand: 16
  oxe_droid: 17
  oxe_fractal: 18
  oxe_language_table: 19
  oxe_bridge: 20
  real_panda_single_arm: 21
  hot3d_hands_only: 23
  gr1_unified: 24
  robocasa_gr1_arms_waist_fourier_hands: 25
  agibot: 26
  lapa: 27
  oxe_mutex: 28
  oxe_roboset: 29
  oxe_plex: 30
  dream: 31
  xdof: 22
  gr1_unified_segmentation: 14
  language_table_sim: 7
  gr1_isaac: 0
  sim_behavior_r1_pro: 31
  mecka_hands: 27
  real_r1_pro_sharpa: 28
